### ISSUE TITLE
Module does not work

### ISSUE THREAD

**Issue by Aetet** [steelbrain/declarations-js#10] opened 2016-12-23 11:32 UTC
Is this module work? I need this module for:

go to declaration for es6 imports:

```
import Hello from './Hello';
``

go to declaration flow type imports:
```js
import type Hello from './HelloType';
```

Even if I use absolute path inside my project f.e.

```js
import type Hello from 'my-project/common/HelloType';
```

Currently it does not work for any of this case. What keyboard must trigger popup for jump to declaration?

**Comment by steelbrain** [comment] 2016-12-23 11:39
It's mentioned in the README

**Comment by Aetet** [comment] 2016-12-23 11:41
Nope. neither alt+enter or ctrl+enter does not work for me. It even does not show at Keybindings resolver

**Comment by steelbrain** [comment] 2016-12-23 11:43
That's actually really strange, does it show up in the installed packages menu? Does restarting Atom make it's keybindings show? Do you get any error in dev tools?

**Comment by Aetet** [comment] 2016-12-23 11:45
Ok. I get it. i need to install separately Intentions package to make it work.

**Comment by steelbrain** [comment] 2016-12-23 11:46
Oh wow, I thought it auto-installed the intentions package, does it not?

**Comment by Aetet** [comment] 2016-12-23 11:46
Nope. For one file it works like charm. But it stil does not resolve paths for imports. :(

**Comment by steelbrain** [comment] 2016-12-23 11:47
It does actually, what you are saying is really very odd, I'll be able to confirm what you are saying soon and will have an explanation or a fix

**Comment by Aetet** [comment] 2016-12-23 11:47
Ok. Thanks

**Comment by zerkalica** [comment] 2016-12-24 09:49
Confirm it. 

Atom 1.12.6

I install manually flow-ide, declarations, declarations-js

```js
// @flow

import type {A} from '../some'
export type B = {
 a: A;
}
```

If i hold ctrl and press on A in a: A cursor jumps to ``` import type {A} from '../some' ```, but not to
../some

This code is strange:

https://github.com/steelbrain/declarations-js/blob/master/lib/index.js#L22

```js
const FLOW_PACKAGES = ['declarations-flow', 'flow-ide']
...
 if (textEditor.getText().indexOf('/* @flow */') !== -1 && FLOW_PACKAGES.some(name => atom.packages.isPackageActive(name))) {
          // Let the declarations-flow package handle the flow files
          return []
        }
```

Looks like a mock, why return [] ?

[Your declarations wiki](https://github.com/steelbrain/declarations/wiki/Provider-API) says return something like this:

```js
 return [
          {
            range: [[0, 0], [0, 4]],
            source: {
              filePath: '/tmp/test.txt',
              position: [5, 0]
            }
          },
          {
            range: [[1, 0], [1, 4]],
            source: {
              filePath: '/tmp/test.txt'
            }
          }
        ]
```

Does declarations-js really supports jump to declaration for flowtype ?

**Comment by steelbrain** [comment] 2016-12-24 10:27
Hi @zerkalica, sorry about that, was overlooked test code that I forgot to remove, if you upgrade to v1.0.2 of this package it should be working well with `flow-ide` enabled.

Also @Aetet if you look at this image, you'll see that the variables are jumped to between the file, but if you click on the import path of the file you can actually jump to the file, I got that view in the image by holding the alt (options) key

<img src="https://cloud.githubusercontent.com/assets/4278113/21466430/5869dfa4-c980-11e6-92dc-c41384221789.png">

Closing as I've personally confirmed it to be working, but please do feel free to continue discussing

**Closed as completed by steelbrain** 2016-12-24 10:27 UTC

**Comment by zerkalica** [comment] 2016-12-24 10:55
Ok, but after updating declarations-js to 1.0.2 and restarting atom nothing has changed.

Cursor still jumps to to import type {A} from '../some', but not to
../some file

It feature works for you?

**Comment by steelbrain** [comment] 2016-12-24 10:57
@zerkalica That is actually working as intended, cursor jumps to `import type {A} from '../some'` because that's where it was defined, what you should do to open that file is select the string `../some` and try to jump to declaration on it, then you'll be taken to the file

**Comment by zerkalica** [comment] 2016-12-24 11:07
I need to view declaration instead of import this declaration. This behaviour in common ides, like idea for java.

It's hard to implement some option, that skips unnecessary import jump and directly moving to siutable file and position?

**Comment by steelbrain** [comment] 2016-12-24 11:09
I would be happy to implement it, but the title of the bug report that we're discussing in is misleading as it does work, just not the best way.

Can you open a new issue for it? It'd be pretty useful for me too because I use this package often myself :)

**Comment by zerkalica** [comment] 2016-12-24 11:16
Ok, in what project? declarations, declarations-js or flow-ide ?
=)

**Comment by steelbrain** [comment] 2016-12-24 11:16
`declarations-js` (this) package please :)
